variable "region" {
  description = "AWS region to deploy into."
  type        = string
  default     = "eu-west-3" # Paris
}

variable "env_name" {
  description = "Environment/stack name, used in resource names and SSM parameter paths."
  type        = string
  default     = "demo"
}

variable "domain" {
  description = "Public domain the APIs are served under. Empty (default) uses the Elastic IP with a self-signed internal certificate (cms on :443, users on :8443). When set, requires route53_zone_id and issues Let's Encrypt certificates for cms.<domain> and users.<domain>."
  type        = string
  default     = ""
}

variable "route53_zone_id" {
  description = "Route 53 hosted zone id for `domain`; only used when `domain` is set."
  type        = string
  default     = ""
}

variable "instance_type" {
  description = "EC2 instance type. Default t4g.small is free-trial eligible (through 2026-12-31) and has 2 GiB of RAM; downgrade to t4g.micro (1 GiB) after the trial ends."
  type        = string
  default     = "t4g.small"
}

variable "instance_arch" {
  description = "Instance CPU architecture: arm64 (t4g.*) or x86_64 (t3./t2.). Must match instance_type."
  type        = string
  default     = "arm64"
}

variable "ebs_size_gb" {
  description = "Size in GiB of the EBS store volume mounted at /var/lib/queue-api."
  type        = number
  default     = 8
}

variable "cms_password" {
  description = "Password of the reserved cms-webhook user. Generated by scripts/bootstrap-aws.sh at environment creation; never the committed local-development default."
  type        = string
  sensitive   = true
}

variable "admin_password" {
  description = "Password of the reserved administrator user. Generated by scripts/bootstrap-aws.sh at environment creation."
  type        = string
  sensitive   = true
}

variable "regular_password" {
  description = "Password of the reserved regular-user user. Generated by scripts/bootstrap-aws.sh at environment creation."
  type        = string
  sensitive   = true
}

variable "auth_db_connection" {
  description = "Connection string for the shared credential store (SQLite), stored in SSM as a SecureString."
  type        = string
  sensitive   = true
  default     = "Data Source=/var/lib/queue-api/queue-auth.db"
}

variable "cms_db_connection" {
  description = "Connection string for the shared CMS event store (SQLite), stored in SSM as a SecureString."
  type        = string
  sensitive   = true
  default     = "Data Source=/var/lib/queue-api/queue-cms.db;Default Timeout=30"
}

variable "github_org" {
  description = "GitHub organization or username that owns the repository; used to scope the CI deploy OIDC role. Leave empty to skip the OIDC role."
  type        = string
  default     = ""
}

variable "github_repo" {
  description = "Optional repository name to scope the OIDC role to a single repo; empty allows the whole organization."
  type        = string
  default     = ""
}

variable "bucket_suffix" {
  description = "Optional suffix appended to the artifact bucket name (bucket names are globally unique)."
  type        = string
  default     = ""
}
